### ISSUE TITLE
Continuous Recognition

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [Funnyguy77/PocketSphinxUnityDemo#13]
You mention in [another issue](https://github.com/Funnyguy77/PocketSphinxUnityDemo/issues/2#issuecomment-587085241) that it would be possible to continuously listen, then trim when speaking starts and stops.  I didn't see any obvious way to accomplish that , could you point me in the right direction?

I'm working on an experiment in Quest where keywords could be recognized, which trigger various actions in the 3d world.

**Comment by Funnyguy77** [comment]
Explained in #17
