### ISSUE TITLE
I am new to PocketSphinxUnityDemo

### ISSUE THREAD

**Issue by spencergong** [Funnyguy77/PocketSphinxUnityDemo#14]
I hit the space key for recording and then stop the recording. Nothing happened. 

Could you please tell me how to run your demo in details.

Thanks.
Spencer

**Comment by Funnyguy77** [comment]
Hi Spencer!

Thanks for checking out the PocketSphinx demo for Unity. 

Usage & installation should be as follows:
- Clone this project and open it in your version of Unity. (Note: Downloading a zip file using the green button on Github does not work. You must clone the Project with a version of git that has LFS.)
- Once installed open the scene labeled "ExampleScene"
- Once in play mode, you should see a prompt on the screen saying "Say -  [There will be some phrase here]"
- Press space-bar to begin recording.
- Speak the phrase. (default is: "this is a test")
- Press space-bar to stop recording.
- If recognized you should see the screen update saying "Keyphrase recognized!"

Notes:
- The current microphone in use should be listed in the bottom left corner.

**Comment by Funnyguy77** [comment]
Closing this issue as their hasn't been an update for some time. Please re-open if you're still encountering this issue.
