### ISSUE TITLE
Extract phonmes from speech?

### ISSUE THREAD

**Issue by johnnymurf** [Funnyguy77/PocketSphinxUnityDemo#26]
Hey trying adapt pocketsphinx for a phoneme recognition project in Untiy.
Would it be possible using the libraries project do you think?

**Comment by Funnyguy77** [comment]
Hi! 

Yes, this is technically possible. But you would probably have better luck with Microsoft's implementation of this. You can view their repository here. [[Link]](https://github.com/microsoft/PhoneticMatching)

Ideally you could combine Sphinx with Microsoft's repository to create a high accuracy phoneme recognition project. I've attempted this before, and it did work fairly well. But I sadly no longer have the project. 

Hope this helps. 

Best,
Wright E.
