### ISSUE TITLE
libpocketsphinxwrap doesn't work on il2cpp

### ISSUE THREAD

**Issue by Virus-vr** [Funnyguy77/PocketSphinxUnityDemo#29]
It works great on mono but for some reason simply switching from mono to il2cpp, while staying on the same architecture breaks it.
I'm also not getting any meaningful errors as the only exception I was able to catch was this
> The type initializer for 'Pocketsphinx.pocketsphinxPINVOKE' threw an exception

I also tried using the ARmx64 .so file linked here [here](https://github.com/NielsMasdorp/Speculum-Android/tree/master/app/src/main/jniLibs/arm64-v8a), but it doesn't change anything.

**Comment by Virus-vr** [comment]
I found a more useful way to debug this and got all of these messages

> 2024.08.06 01:52:15.012 15303 15340 Error Unity <color=red>Exception during decoder configuration:The type initializer for 'Pocketsphinx.pocketsphinxPINVOKE' threw an exception.The type initializer for 'Pocketsphinx.pocketsphinxPINVOKE.SWIGExceptionHelper' threw an exception.System.EntryPointNotFoundException: Unable to find an entry point named 'SWIGRegisterExceptionCallbacks_pocketsphinx' in 'pocketsphinxwrap'. Tried the following entry points: Unable to get function 'SWIGRegisterExceptionCallbacks_pocketsphinx' because of 'The requested function was not found (0x06000001) dlerror() = undefined symbol: SWIGRegisterExceptionCallbacks_pocketsphinx

I will look into this some more but all of this is a bit new to me

**Comment by Virus-vr** [comment]
I found a temporary solution by adding [MonoPInvokeCallback(typeof(ExceptionArgumentDelegate))] to many of the methods in SphinxBasePINVOKE.cs and SphinxPINVOKE.cs.
Now I tried to switch from ARMv7 to ARM_64 (v8) and the .so file from the build does not work anymore.
I have no idea how I can build the .so file since I don't know which source files or programs/processes where used.
I'm aware that there was an already build ARM_64 .so file linked [here](https://github.com/Funnyguy77/PocketSphinxUnityDemo/issues/16#issuecomment-642937939) but that file has completely different headers so I'm not sure I could use that.

**Comment by Funnyguy77** [comment]
Nice work. Yes, most likely you will need to find and build your own ARM_64 library supporting IL2CPP.

Sorry I am not more help, I haven't touched this project in years. But it seems like you are on the right track. These days I mostly use the Azure based Microsoft Speech Recognizer. I've found it to be much more accurate than Sphinx, but you do need an active internet connection.

**Comment by Virus-vr** [comment]
I found this repo which has working shared object files for arm64 as well. https://github.com/yolanother/UnityPocketSphinx
I marked this as closed since this solved my problem.
