### ISSUE TITLE
Use language model without compress .tar file

### ISSUE THREAD

**Issue by tienlx91** [Funnyguy77/PocketSphinxUnityDemo#4]
Hello, I already trained a custom model that generate all the files:
- variances
- transition_matrices
- noisedict
- mixture_weights
- means
- mdef
- feat.params
- en-us.lm.bin (convert from en-us.lm using sphinx_lm_convert)

On project /StreamingAssets, you use a .tar compress file. I've compress all my files to .zip exact same structure as yours using WinRAR. Then convert to .rar.

I replace the en-us.tar by my .tar file. When I run it show an error. Is there anyway I can use without using .tar file?

Error:
FormatException: Could not find any parsable digits.
System.ParseNumbers.StringToInt (System.String value, System.Int32 fromBase, System.Int32 flags, System.Int32* parsePos) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.ParseNumbers.StringToInt (System.String value, System.Int32 fromBase, System.Int32 flags) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Convert.ToInt32 (System.String value, System.Int32 fromBase) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
TarCs.TarHeader.UpdateHeaderFromBytes () (at Assets/Scripts/TarReader/TarHeader.cs:110)
TarCs.UsTarHeader.UpdateHeaderFromBytes () (at Assets/Scripts/TarReader/UsTarHeader.cs:85)
TarCs.TarReader.MoveNext (System.Boolean skipData) (at Assets/Scripts/TarReader/TarReader.cs:213)
TarCs.TarReader.ReadToEnd (System.String destDirectory) (at Assets/Scripts/TarReader/TarReader.cs:45)
SphinxExample+<Decompress>d__20.MoveNext () (at Assets/Scripts/SphinxExample.cs:242)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

![image](https://user-images.githubusercontent.com/3906860/75609577-62aea700-5b3c-11ea-91eb-897d3ce8fd84.png)

**Comment by antonshkurenko** [comment]
@tienlx91 how did you solve that?

**Comment by tienlx91** [comment]
I have to use the .tar by open CMD and type this command 
`tar cvf jp.tar jp`, where `jp.tar` is the target and `jp` is the folder
