### ISSUE TITLE
DLLNotFoundException

### ISSUE THREAD

**Issue by jin-archipin** [Funnyguy77/PocketSphinxUnityDemo#5]
![image](https://user-images.githubusercontent.com/58724408/75936929-dfd47600-5ec6-11ea-96a0-a4d3ac18bf40.png)

I was able to play when I tried in my office, but now there is an DLL error...
Does anyone know what did I wrong??

OS : Windows 10 64bit
Unity : 2018.4.13f1 (same as project default)

**Comment by jin-archipin** [comment]
![image](https://user-images.githubusercontent.com/58724408/75937381-08a93b00-5ec8-11ea-970e-8f96a6a48234.png)

**Comment by chubillkelvin** [comment]
Did you import all the folders / files from the demo project to your own project?

This happened to me once before, and the solution was to open the demo project as an existing project. Hope this helps!

**Comment by jin-archipin** [comment]
This is the project itself. I just cloned it and opened it.

**Comment by jin-archipin** [comment]
I tried reimport all, delete dlls and import the dlls again, and neither of them works... :(

**Comment by chubillkelvin** [comment]
Just a wild guess here, does the complete path to your project folder includes non-English characters? For example, you may have Japanese / Korean / Chinese characters in your user path name. Not sure if it helps, but sometimes when it says certain thing could not be found, this could be the problem.

**Comment by jin-archipin** [comment]
Nah... I use English Windows and the path is C:\Users\Jin\ws\PocketSphinxUnityDemo

**Comment by chubillkelvin** [comment]
Did you install `git-lfs` before cloning the project? The file missing could be due to this.

If this doesn't help, I guess I am out of thoughts here.

**Comment by jin-archipin** [comment]
![image](https://user-images.githubusercontent.com/58724408/75950819-abc07b80-5eed-11ea-978c-b037342fccdd.png)
I use embedded git of sourcetree. I guess I don't have any missing files. I have dlls but it just isn't found...

**Comment by jin-archipin** [comment]
![image](https://user-images.githubusercontent.com/58724408/76058728-851f4500-5fc0-11ea-984b-8437f1704111.png)

While I was trying anything I can do, I found out the error message is little different in Unity 2019.3.3
Maybe I need to install some dependencies to use libpocketsphinxwrap. @Funnyguy77 Do you have any idea?

Edit: Only thing I need to do is to figure out what is the ??? thing below
![image](https://user-images.githubusercontent.com/58724408/76059034-2dcda480-5fc1-11ea-85b2-16f82122c262.png)

**Comment by jin-archipin** [comment]
OMG I solved it!!
Since I hate Visual Studio and my computer was new, I didn't have MSVCR110.dll.
https://www.microsoft.com/en-us/download/details.aspx?id=30679#
I installed it and it works find now!
YAY~

**Comment by Funnyguy77** [comment]
Hey so sorry for the delayed response on this! I've been extremely busy as of late. 

Glad to see you were able to resolve your issue! :)

**Comment by jin-archipin** [comment]
@Funnyguy77 It's okay man. You helped me a lot already!

**Comment by Znoleg** [comment]
Update: downloading just MSVCR110.dll didn't fix my problem. Also downloaded latest visual c++ redistributable packages for x64/x86/arm architectures and now it works!

**Comment by sovannoup** [comment]
I apologize for jumping on this thread again. But I did download and install latest visual c++ redistributable packages and I also have MSVCR110.dll but still the above errors exist. Could anyone explain why?
