### ISSUE TITLE
Error using jsfg file

### ISSUE THREAD

**Issue by oopss00** [Funnyguy77/PocketSphinxUnityDemo#8]
Hello. As an example you posted, I ask because there are some parts of the test that are not possible.

for example

#JSGF v1.0;

grammar command;

public <command> = <command1>;

<command1> = <number1> <number> <number>;

<number> = Zero | One | Two | Three | Four | Five | Six | Seven | Eight | Nine;

<number1> = Zero | One | Two | Three;

Create a Gramar file as shown above. 

In the ExampleScene that you uploaded, 

c.SetString("-keyphrase", keyphrase)  -> c.SetString("-jsgf", jsgfPath)

Unity error report has occurred. 

Can you give me a brief example of Grammar?

**Comment by jin-archipin** [comment]
I'm not an expert of jsgf files, but you can check this link below.
I don't see any line "grammer command" here
https://cmusphinx.github.io/wiki/pocketsphinx_pronunciation_evaluation/

**Comment by Funnyguy77** [comment]
There hasn't been an update on this in some time. Is this still an issue? Please re-open if you're still encountering this.
