### ISSUE TITLE
Unity crash always

### ISSUE THREAD

**Issue by z3nth10n** [Funnyguy77/PocketSphinxUnityDemo#9]
Well, I have a problem. Unity crashes at any time that I play the scene, I reviewed the issues and this is caused because of the library is looking for the Language Model.

I tried cloning the repository using `git lfs clone ...`, but this neither works.

**Comment by Funnyguy77** [comment]
Hey there! 

I'm sorry to hear that you're having some trouble with the PocketSphinx example. Although I'm going to need some more information here. Do you encounter any errors when Unity crashes? 

Also could you check the size of your language model file, then provide me with the file-size? 

Thanks!

**Comment by z3nth10n** [comment]
Hi @Funnyguy77, I don't any idea if I have any language model file, does this repo include one?

Also, if not, where can I find one? I don't exactly how to build although I know where is the tutorial on the official cmusphinx website.

Thanks for your quick response!

**Comment by jin-archipin** [comment]
Here it is 
Assets/StreamingAssets/en-us.tar

**Comment by z3nth10n** [comment]
Ok, I have this file, but I don't see any reference of "StreamingAssets" in code, neither any unzip method and neither any documentation related about what to do with this file. Sorry, I'm missing something. Thanks for your help @jin-archipin !!

**Comment by Funnyguy77** [comment]
Closing thread, is this still an issue? Please reopen if it is.
